name: N3rdyKits
version: 1.0
description: Plugin de KitPvP
author: N3rdyDev
main: com.n3rdydev.main
commands:
  build:
    description: modo construcao
    permission-message: §cNão possui permissão.
    usage: /build
  kits:
    description: abre menu de kits.
    permission-message: §cNão possui permissão.
    usage: /kits
    aliases:
      - kit
  n3rdykits:
    description: plugin comandos.
    permission-message: §cNão possui permissão.
    usage: /n3rdykits <função>
  admin:
    description: invisibilidade para outros jogadores.
    permission-message: §cNão possui permissão.
    usage: /admin
  gm:
    description: troca de gamemode.
    permission-message: §cNão possui permissão.
    usage: /gm [0/1]
  score:
    description: Ativa/desativa scoreborad.
    permission-message: §cNão possui permissão.
    usage: /score
  chat:
    description: limpar mensagem dos chat.
    permission-message: §cNão possui permissão.
    usage: /chat [ativar/desativar/limpar]
  suicidar:
    description: morre.
    permission-message: §cNão possui permissão.
    usage: /suicidar
    aliases:
      - morrer
  warps:
    description: lista de warps.
    permission-message: §cNão possui permissão.
    usage: /warps
    aliases:
      - warp
  spawn:
    description: teleporte spawn.
    permission-message: §cNão possui permissão.
    usage: /spawn
  tpall:
    description: teleporta todo mundo para a posição do staff.
    permission-message: §cNão possui permissão.
    usage: /tpall
  tphere:
    description: teleporta um jogador especifico para a posição do staff.
    permission-message: §cNão possui permissão.
    usage: /tpall [jogador]
  anunciar:
    description: envia um anúncio para todos os jogadores.
    permission-message: §cNão possui permissão.
    usage: /anunciar [mensagem]